---
- name: Build container with Ansible
  hosts: localhost
  tasks:
    - name: Stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: Remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: Remove simple-project-img
      command: docker rmi simple-project-img
      ignore_errors: yes

    - name: Build docker image using the Dockerfile
      command: docker build -t simple-project-img .
      register: build_result

    - name: Check if the build was successful
      fail:
        msg: "Docker image build failed!"
      when: build_result.rc != 0

    - name: Run container
      command: docker run -d --name web-container -p 5000:80 simple-project-img